// ListOfShoes.js
const ListOfShoes = [
    {
        id: 1,
        name: "Nike Air Max",
        price: 120,
        color: "White",
        size: 39,
        rating: 4.5,
        category: "Sneakers",
        image: "https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco/b8fe8fa6-7952-440b-9086-b1f1cd169b47/JR+PHANTOM+LUNA+II+CLUB+TF.png",
    },
    {
        id: 2,
        name: "Adidas Ultraboost",
        price: 180,
        color: "Black",
        size: 42,
        rating: 4.5,
        category: "Running",
        image: "https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco/dc3f464a-1b02-4eb9-8fc6-e3abc908f0e6/ZOOM+VAPOR+16+ACADEMY+TF.png",
    },
    {
        id: 3,
        name: "Puma Suede",
        price: 100,
        color: "Blue",
        size: 43,
        rating: 4.5,
        category: "Casual",
        image: "https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco/dc3f464a-1b02-4eb9-8fc6-e3abc908f0e6/ZOOM+VAPOR+16+ACADEMY+TF.png",
    },
    {
        id: 4,
        name: "Converse Chuck Taylor",
        price: 80,
        color: "Red",
        size: 44,
        rating: 4,
        category: "High Tops",
        image: "https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco/dc3f464a-1b02-4eb9-8fc6-e3abc908f0e6/ZOOM+VAPOR+16+ACADEMY+TF.png",
    },
    {
        id: 5,
        name: "Converse Chuck Taylor",
        price: 80,
        color: "Red",
        size: 39,
        rating: 4.5,
        category: "High Tops",
        image: "https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco/dc3f464a-1b02-4eb9-8fc6-e3abc908f0e6/ZOOM+VAPOR+16+ACADEMY+TF.png",
    },
    {
        id: 6,
        name: "Converse Chuck Taylor",
        price: 80,
        color: "Red",
        size: 39,
        rating: 4,
        category: "High Tops",
        image: "https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco/dc3f464a-1b02-4eb9-8fc6-e3abc908f0e6/ZOOM+VAPOR+16+ACADEMY+TF.png",
    },
    {
        id: 7,
        name: "Converse Chuck Taylor",
        price: 80,
        color: "Red",
        size: 40,
        rating: 4,
        category: "High Tops",
        image: "https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco/dc3f464a-1b02-4eb9-8fc6-e3abc908f0e6/ZOOM+VAPOR+16+ACADEMY+TF.png",
    },
    {
        id: 8,
        name: "Converse Chuck Taylor",
        price: 80,
        color: "Red",
        size: 41,
        rating: 4.5,
        category: "High Tops",
        image: "https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco/dc3f464a-1b02-4eb9-8fc6-e3abc908f0e6/ZOOM+VAPOR+16+ACADEMY+TF.png",
    },
];

export default ListOfShoes;
